### PR TITLE
Create Corona timelapse

### LINKED ISSUE #18: Corona timelapse
Germany has lifted the travel restrictions for all regions upon the mildness of the omicron variant.

Since this renders the site quite uninteresting, I suggest to collect all the risk levels for each country over time so that some nice visualization can be implemented. This can be broken down into two tasks:

1. The creation of a table with all the risk levels over time, assigned to @rodrihgh 
2. The (probably R-based) visualization, assigned to @dieghernan 

My plan for the table is to have it as a CSV with the following structure:

|  | COUNTRY_ISO_CODE_A | COUNTRY_ISO_CODE_B | ... |
| --- | --- | --- | --- |
| date_1 | risk_code1.A | risk_code1.B | ... |
| date_2 | risk_code2.A | risk_code2.B | ... |
| ... | ...  | ...  | ...  |

### PR DESCRIPTION
**Pull request by dieghernan**
Close #18 

This is now complete. I leave the merge of this PR to you @rodrihgh , as the sponsor of the feature

### CODE REVIEW

**Comment by dieghernan** [comment]
Oops! Small bug, I will tell you

**Comment by dieghernan** [comment]
Now it is done

**Comment by rodrihgh** [comment]
Working on this, two requests to @dieghernan :
1. The gif has not been updated after https://github.com/dieghernan/RKI-Corona-Atlas/pull/21/commits/76884b0e27d101a5477a4f6f9ffefbeb83d9bd02 , https://github.com/dieghernan/RKI-Corona-Atlas/pull/21/commits/9092464abc948b67ab5d30a666584b4d03e7477d . Do you want to double check?
2. What about crediting yourself on the gif, something like _Credit: @[your twitter/github handle]_ on the bottom left corner?

**Comment by dieghernan** [comment]
Hi @rodrihgh 

After https://github.com/dieghernan/RKI-Corona-Atlas/pull/21/commits/00016454df009b049e8cab934734932505c12aa8 request 1) is updated. It didn’t update automatically with the current setup because it was not designed in that way:

- Daily snapshots are stored to improve performance. If anything in the map (like colores) is changed then the cache should be rebuilt with  https://github.com/dieghernan/RKI-Corona-Atlas/actions/runs/1979650975
- On production, the action just creates the new daily snapshots with the main action and create the gif. It should work 

Regarding the other suggestion, I appreciate but I am ok as it is right now 👍🏻

**Pull request merged**
